import type { ResumeData, ResumeSectionKey, ResumeVisibility } from '../types';

interface Props {
  data: ResumeData;
  visibility: ResumeVisibility;
  onChange: (data: ResumeData) => void;
  onVisibilityChange: React.Dispatch<React.SetStateAction<ResumeVisibility>>;
}

const keyFor = (section: ResumeSectionKey, index: number) => `${section}.${index}`;
const isVisible = (state: ResumeVisibility, section: ResumeSectionKey, index: number) => state.items[keyFor(section, index)] ?? true;
const move = <T,>(items: T[], index: number, offset: number) => {
  const next = [...items];
  [next[index], next[index + offset]] = [next[index + offset], next[index]];
  return next;
};

const Field = ({ label, value, onChange, long = false }: { label: string; value: string; onChange: (value: string) => void; long?: boolean }) => (
  <label className="form-field"><span>{label}</span>{long ? <textarea value={value} onChange={(event) => onChange(event.target.value)} /> : <input value={value} onChange={(event) => onChange(event.target.value)} />}</label>
);

const Controls = ({ index, length, remove, reorder }: { index: number; length: number; remove: () => void; reorder: (offset: number) => void }) => (
  <div className="item-actions"><button aria-label="上移" disabled={index === 0} onClick={() => reorder(-1)} type="button">↑</button><button aria-label="下移" disabled={index === length - 1} onClick={() => reorder(1)} type="button">↓</button><button onClick={remove} type="button">删除</button></div>
);

const Bullets = ({ values, onChange, label = '要点' }: { values: string[]; onChange: (values: string[]) => void; label?: string }) => (
  <div className="list-editor">{values.map((value, index) => <div className="list-row" key={`${index}-${value}`}><textarea aria-label={`${label}${index + 1}`} value={value} onChange={(event) => onChange(values.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} /><button aria-label={`删除${label}`} onClick={() => onChange(values.filter((_, itemIndex) => itemIndex !== index))} type="button">×</button></div>)}<button className="text-action" onClick={() => onChange([...values, ''])} type="button">+ 添加{label}</button></div>
);

const ResumeForm = ({ data, visibility, onChange, onVisibilityChange }: Props) => {
  const toggle = (section: ResumeSectionKey, index: number) => onVisibilityChange((current) => ({ ...current, items: { ...current.items, [keyFor(section, index)]: !isVisible(current, section, index) } }));
  const toggleSection = (section: ResumeSectionKey) => onVisibilityChange((current) => ({ ...current, sections: { ...current.sections, [section]: !current.sections[section] } }));
  const changeBasics = (key: keyof ResumeData['basics'], value: string) => onChange({ ...data, basics: { ...data.basics, [key]: value } });

  return <div className="resume-form">
    <section className="form-section"><div className="section-heading"><div><p className="eyebrow">CONTENT</p><h2>基础信息</h2></div></div><div className="field-grid"><Field label="姓名" value={data.basics.name} onChange={(value) => changeBasics('name', value)} /><Field label="求职方向" value={data.basics.role ?? ''} onChange={(value) => changeBasics('role', value)} /><Field label="邮箱" value={data.basics.email} onChange={(value) => changeBasics('email', value)} /><Field label="个人网站" value={data.basics['personal-website']} onChange={(value) => changeBasics('personal-website', value)} /><Field label="研究领域" long value={data.basics.field ?? ''} onChange={(value) => changeBasics('field', value)} /><Field label="个人简介" long value={data.basics.about ?? ''} onChange={(value) => changeBasics('about', value)} /></div></section>

    <section className="form-section"><div className="section-heading"><div><p className="eyebrow">CONTENT</p><h2>教育经历</h2></div><button className="text-action" onClick={() => toggleSection('education')} type="button">{visibility.sections.education ? '隐藏区块' : '显示区块'}</button></div>{data.education.map((item, index) => <div className="form-item" key={`${item.institution}-${index}`}><div className="item-heading"><strong>{item.institution || '未命名教育经历'}</strong><button className="visibility-action" onClick={() => toggle('education', index)} type="button">{isVisible(visibility, 'education', index) ? '显示中' : '已隐藏'}</button><Controls index={index} length={data.education.length} remove={() => onChange({ ...data, education: data.education.filter((_, i) => i !== index) })} reorder={(offset) => onChange({ ...data, education: move(data.education, index, offset) })} /></div><div className="field-grid"><Field label="学校" value={item.institution} onChange={(value) => onChange({ ...data, education: data.education.map((entry, i) => i === index ? { ...entry, institution: value } : entry) })} /><Field label="学位" value={item.studyType} onChange={(value) => onChange({ ...data, education: data.education.map((entry, i) => i === index ? { ...entry, studyType: value } : entry) })} /><Field label="专业" value={item.area} onChange={(value) => onChange({ ...data, education: data.education.map((entry, i) => i === index ? { ...entry, area: value } : entry) })} /><Field label="起止时间" value={`${item.startDate} - ${item.endDate}`} onChange={(value) => { const [startDate = '', endDate = ''] = value.split(' - '); onChange({ ...data, education: data.education.map((entry, i) => i === index ? { ...entry, startDate, endDate } : entry) }); }} /></div><Bullets label="课程" values={item.courses} onChange={(courses) => onChange({ ...data, education: data.education.map((entry, i) => i === index ? { ...entry, courses } : entry) })} /></div>)}<button className="text-action" onClick={() => onChange({ ...data, education: [...data.education, { institution: '', location: '', area: '', studyType: '', startDate: '', endDate: '', courses: [] }] })} type="button">+ 添加教育经历</button></section>

    <section className="form-section"><div className="section-heading"><div><p className="eyebrow">CONTENT</p><h2>相关经历</h2></div><button className="text-action" onClick={() => toggleSection('experience')} type="button">{visibility.sections.experience ? '隐藏区块' : '显示区块'}</button></div>{data.experience.map((item, index) => <div className="form-item" key={`${item.position}-${index}`}><div className="item-heading"><strong>{item.position || '未命名经历'}</strong><button className="visibility-action" onClick={() => toggle('experience', index)} type="button">{isVisible(visibility, 'experience', index) ? '显示中' : '已隐藏'}</button><Controls index={index} length={data.experience.length} remove={() => onChange({ ...data, experience: data.experience.filter((_, i) => i !== index) })} reorder={(offset) => onChange({ ...data, experience: move(data.experience, index, offset) })} /></div><div className="field-grid"><Field label="组织" value={item.company ?? item.institution ?? item.name ?? ''} onChange={(value) => onChange({ ...data, experience: data.experience.map((entry, i) => i === index ? { ...entry, company: value, institution: undefined } : entry) })} /><Field label="职位" value={item.position} onChange={(value) => onChange({ ...data, experience: data.experience.map((entry, i) => i === index ? { ...entry, position: value } : entry) })} /><Field label="开始时间" value={item.startDate} onChange={(value) => onChange({ ...data, experience: data.experience.map((entry, i) => i === index ? { ...entry, startDate: value } : entry) })} /><Field label="结束时间" value={item.endDate} onChange={(value) => onChange({ ...data, experience: data.experience.map((entry, i) => i === index ? { ...entry, endDate: value } : entry) })} /></div><Bullets values={item.description ?? (item.summary ? [item.summary] : [])} onChange={(description) => onChange({ ...data, experience: data.experience.map((entry, i) => i === index ? { ...entry, description } : entry) })} /></div>)}<button className="text-action" onClick={() => onChange({ ...data, experience: [...data.experience, { company: '', position: '', startDate: '', endDate: '', description: [] }] })} type="button">+ 添加经历</button></section>

    <section className="form-section"><div className="section-heading"><div><p className="eyebrow">CONTENT</p><h2>技能</h2></div><button className="text-action" onClick={() => toggleSection('skills')} type="button">{visibility.sections.skills ? '隐藏区块' : '显示区块'}</button></div>{data.skills.map((item, index) => <div className="form-item compact-item" key={`${item.category}-${index}`}><div className="item-heading"><strong>{item.category ?? item.name ?? '技能分类'}</strong><Controls index={index} length={data.skills.length} remove={() => onChange({ ...data, skills: data.skills.filter((_, i) => i !== index) })} reorder={(offset) => onChange({ ...data, skills: move(data.skills, index, offset) })} /></div><Field label="分类" value={item.category ?? item.name ?? ''} onChange={(value) => onChange({ ...data, skills: data.skills.map((entry, i) => i === index ? { ...entry, category: value } : entry) })} /><Field label="关键词（逗号分隔）" value={item.keywords.join(', ')} onChange={(value) => onChange({ ...data, skills: data.skills.map((entry, i) => i === index ? { ...entry, keywords: value.split(',').map((word) => word.trim()).filter(Boolean) } : entry) })} /></div>)}<button className="text-action" onClick={() => onChange({ ...data, skills: [...data.skills, { category: '', keywords: [] }] })} type="button">+ 添加技能分类</button></section>
    <section className="form-section"><div className="section-heading"><div><p className="eyebrow">CONTENT</p><h2>个人项目</h2></div><button className="text-action" onClick={() => toggleSection('projects')} type="button">{visibility.sections.projects ? '隐藏区块' : '显示区块'}</button></div>{(data.projects ?? []).map((item, index) => <div className="form-item" key={`${item.name}-${index}`}><div className="item-heading"><strong>{item.name || '未命名项目'}</strong><button className="visibility-action" onClick={() => toggle('projects', index)} type="button">{isVisible(visibility, 'projects', index) ? '显示中' : '已隐藏'}</button><Controls index={index} length={(data.projects ?? []).length} remove={() => onChange({ ...data, projects: (data.projects ?? []).filter((_, i) => i !== index) })} reorder={(offset) => onChange({ ...data, projects: move(data.projects ?? [], index, offset) })} /></div><div className="field-grid"><Field label="项目名称" value={item.name} onChange={(value) => onChange({ ...data, projects: (data.projects ?? []).map((entry, i) => i === index ? { ...entry, name: value } : entry) })} /><Field label="链接" value={item.link ?? ''} onChange={(value) => onChange({ ...data, projects: (data.projects ?? []).map((entry, i) => i === index ? { ...entry, link: value } : entry) })} /></div><Bullets values={item.description ?? []} onChange={(description) => onChange({ ...data, projects: (data.projects ?? []).map((entry, i) => i === index ? { ...entry, description } : entry) })} /></div>)}<button className="text-action" onClick={() => onChange({ ...data, projects: [...(data.projects ?? []), { name: '', description: [] }] })} type="button">+ 添加项目</button></section>
  </div>;
};

export default ResumeForm;
